blank_issues_enabled: true
contact_links:
  - name: Documentation Issues
    url: https://github.com/Perl/perl5/issues
    about: Please report issues with the contents of documentation to the official Perl issue tracker.
  - name: CPAN Modules
    url: https://metacpan.org
    about: Please report issues with CPAN modules in their preferred bugtracker as indicated on their MetaCPAN page.
